import Head from 'next/head'

import axios from "axios";
import {useEffect, useState} from "react";
import BasicCard from "./card";
import SearchAppBar from "./appbar";




export default function Home() {
    const [load,setLoad] = useState(true)
    useEffect( ()=>{
        async function Ax(){
            const res = await axios.get("/api/getall");
            // console.log(res)
            let data = res.data.recipe.alldata
            setLoad(false)

            data = data.filter((single)=>{
                 return single.title
            })
            setMine(data)
        }
        Ax()
    },[])
    const [mined,setMine] = useState()

    console.log( mined)



  return (
    <>
      <Head>
        <title>Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
          <script src="https://cdn.tailwindcss.com"></script>
      </Head>
      {load? <p>loading</p>:<SearchAppBar mined={mined} setmined={setMine}/>}

     <div className={"flex flex-wrap w-screen justify-center mt-[5vh]"}>
         {load? <p>loading</p>:
         mined.map((single,index)=>{
             return <div className={"flex w-[150px] h-[200px]   m-5"}><BasicCard value={single}/></div>


         })
         }

     </div>
    </>)
}


